# Generated by Django 4.2.7 on 2023-11-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="end",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="ing",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="level",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="user",
            name="point",
            field=models.IntegerField(default=0),
        ),
    ]
