# Generated by Django 4.2.7 on 2023-11-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_user_end_user_ing_user_level_user_point"),
    ]

    operations = [
        migrations.CreateModel(
            name="Items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("minprice", models.IntegerField()),
                ("description", models.TextField()),
                ("img", models.ImageField(null=True, upload_to="items")),
            ],
            options={
                "verbose_name": "아이템",
                "verbose_name_plural": "아이템",
                "db_table": "items",
            },
        ),
    ]
