# Generated by Django 4.2.7 on 2023-11-03 07:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_items"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="items",
            options={"verbose_name": "상품", "verbose_name_plural": "상품"},
        ),
    ]
